### ISSUE TITLE
Ссылка в шапке "курсы" ведет на страницу профессий

### ISSUE THREAD

**Issue by amshkv** [Hexlet/hexletguides.github.io#119]
Стоит поправить ссылку на верную
Добавить ссылку на курсы\профессию

**Comment by Nowitty** [comment]
Я возьмусь

**Comment by Nowitty** [comment]
сделано) потом и кровью

**Comment by JohnConnor1969** [comment]
смержили а ишью не закрыли?

**Comment by amshkv** [comment]
Странно, вроде автоматически должно закрыться
Спасибо что обратили внимание!)
