### ISSUE TITLE
Ссылки в блоке "Содержание страницы"

### ISSUE THREAD

**Issue by BabayevEldar** [Hexlet/hexletguides.github.io#128]
Ссылки в блоке "Содержание страницы" ведут на внешние ресурсы (сайты по ссылке), вместо того чтобы прокручивать страницу к нужному абзацу. Это непривычно и мешает нормальной навигации по странице.

**Comment by sergey-nechaev** [comment]
@BabayevEldar Не могу повторить. Вот тут - https://guides.hexlet.io/https-yandex-guide/, например, есть проблема?

**Comment by BabayevEldar** [comment]
https://guides.hexlet.io/how-to-be-a-helpful-for-the-hexlet-community/

вот тут есть

**Comment by sergey-nechaev** [comment]
Подтверждаю

**Comment by MityaDementiy** [comment]
https://github.com/Hexlet/hexletguides.github.io/pull/136
