### ISSUE TITLE
Двойные кавычки ломают OG-теги

### ISSUE THREAD

**Issue by Melodyn** [Hexlet/hexletguides.github.io#176]
Если в заголовке имеются кавычки, они могут сломать некоторые теги для соцсетей. Пример того что получилось в коде, и при шаринге ссылки:
![image (2)](https://user-images.githubusercontent.com/26752238/104916988-dbf8f780-59a3-11eb-9b5b-6c068a9f9c03.png)
![image (3)](https://user-images.githubusercontent.com/26752238/104916998-de5b5180-59a3-11eb-96db-05fea893583e.png)

**Comment by mokevnin** [comment]
@amshkv победили?

**Comment by amshkv** [comment]
Не помню чтобы мы с этим что-то делали, но сейчас проверил, кавычки внутри тегов/og-тегов меняются на другой тип и не ломают html 
`content="Что такое “управление конфигурацией”?"`
