### ISSUE TITLE
Links open in the same window 

### ISSUE THREAD

**Issue by amshkv** [Hexlet/hexletguides.github.io#178]
Ссылки на внешние сервисы открываются в этом же окне, а стоит открывать в новом

**Comment by zhabinka** [comment]
Есть плагин – https://github.com/keithmifsud/jekyll-target-blank
Но не заработал :(

**Comment by mokevnin** [comment]
Все будет хорошо как переедем на next.js

**Comment by amshkv** [comment]
да
