### ISSUE TITLE
Гайд: что такое компилятор (seo)

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexletguides.github.io#224]
https://guides.hexlet.io/compiler/
В гайд нужно добавить пункт "что такое интерпретатор" в нем написать, что такое интерпретатор и отдельным подпунктом "чем компилятор отличается от интерпретатора "
можно это сделать в конце статьи, перед выводами

**Comment by mokevnin** [comment]
У нас по интерпретатору будет отдельный гайд, этого достаточно для пункта "что такое интерпретатор?"

**Comment by mokevnin** [comment]
Вторую часть добавил, посмотри
