### ISSUE TITLE
Гайд: SSH (seo)

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexletguides.github.io#225]
https://guides.hexlet.io/ssh/
в гайд нужно добавить пункт "чем telnet отличается от ssh"
отдельным параграфом, с подзаголовком. Можно в конец статьи, перед доп ссылками

**Comment by mokevnin** [comment]
Сделал, посмотри плс

**Comment by fey** [comment]
Спросил у Саши в чатике, говорит, что щас ок.
