### ISSUE TITLE
Гайд: Vim (seo)

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexletguides.github.io#226]
https://guides.hexlet.io/vim/
нужно добавить либо в существующий гайд либо сделать отдельный со "шпаргалкой по Vim" (хоткеи и основные команды)

в гайде есть картинка, но она мелкая и её содержимое лучше сделать текстом, это я могу сделать сам, если дадите источник

**Comment by mokevnin** [comment]
Там внутри уже есть небольшая шпаргалка, может просто заголовок добавить? @ashikov поможешь с картинкой?

**Comment by ashikov** [comment]
Да, без проблем. Вернусь из отпуска и займусь.

**Comment by ashikov** [comment]
Шпаргалку в высоком разрешении найти не проблема, вот она: ![vim](https://user-images.githubusercontent.com/676554/141891740-7115d027-143a-4cf5-91e7-22f7b17d76cc.png)

@prio65, а перевод ты тоже можешь сделать или лучше мне? :)

**Comment by mokevnin** [comment]
Перевод делать не надо

**Comment by ashikov** [comment]
Хорошо. В таком случае "источник", который просил @prio65, я предоставил. :)
