### ISSUE TITLE
Как участвовать в жизни Хекслета - добавить проекты

### ISSUE THREAD

**Issue by fey** [Hexlet/hexletguides.github.io#232]
_posts/2019-02-25-how-to-be-a-helpful-for-the-hexlet-community.md

* [x] https://github.com/Hexlet/hexlet-comparator
* [x] https://github.com/Hexlet/jsbrowser
* [x] https://github.com/Hexlet/RestApiTutorial.ru
* [x] https://github.com/Hexlet/react-flowbot-ui-kit

**Comment by mokevnin** [comment]
Еще нодос
