### ISSUE TITLE
Что такое REST

### ISSUE THREAD

**Issue by mokevnin** [Hexlet/hexletguides.github.io#292]

**Comment by fey** [comment]
https://guides.hexlet.io/rest-api/
Закрываем?

**Comment by gomez-git** [comment]
На [главной странице](https://guides.hexlet.io/) отсутствует краткое описание темы @fey @mokevnin 
{
[Что такое время](https://guides.hexlet.io/time/)[](https://guides.hexlet.io/rest-api/)
Как современный компьютер хранит информацию, сколько сейчас времени, как он отсчитывает секунды, почему почти никогда не ошибается и как с этим временем работать
[Что такое REST API?](https://guides.hexlet.io/rest-api/)[](https://guides.hexlet.io/deploy/)
???
[Что такое деплой?](https://guides.hexlet.io/deploy/)
Доставка кода на продакшен сервера. Миграция базы данных. Zero Downtime Deployment. Ansible, Kubernetes
}

**Comment by fey** [comment]
Ага, гайд не дописан :с

**Comment by fey** [comment]
https://github.com/Hexlet/hexletguides.github.io/commit/1fd6e5e61423bfb46f2e58f8cbc7e02890921e59
https://github.com/Hexlet/hexletguides.github.io/commit/ab402246c8241cb89402309d1270094a56ecaea7
https://github.com/Hexlet/hexletguides.github.io/commit/f82716e5d805308138b4bce49b853dc7a6769696
