### ISSUE TITLE
Гайд: виртуализация

### ISSUE THREAD

**Issue by mokevnin** [Hexlet/hexletguides.github.io#31]

**Comment by zhabinka** [comment]
@mokevnin предлагаю @ashikov этот гайд написать. Поможешь конкретизировать тему?
Было дело он блог вёл - https://ln-dev.space/blog.

**Comment by prio65** [comment]
https://guides.hexlet.io/virtualization/
нужно отдельными пунктом добавить - что делать если процессор не поддерживает виртуализацию

**Comment by mokevnin** [comment]
@ashikov фигани плс по принципу, как я сделал в последних коммитах

**Comment by ashikov** [comment]
Добавил вопрос-ответ.

**Comment by fey** [comment]
Гайд есть. Ишшус закрываем?
