### ISSUE TITLE
Необходимо пересмотреть гайд "Как начать разрабатывать в Windows"

### ISSUE THREAD

**Issue by tribals** [Hexlet/hexletguides.github.io#344]
Сейчас гайд содержит много разных вариантов того, как установить окружение для разработки под Windows. Однако многое уже изменилось.

# Пакетный менеджер для Windows

Рекомендуемый в гайде пакетный менеджер Chocolatey имеет множество проблем:
- работает медленно;
- требует административный доступ к компьютеру для установки как его самого, так и пакетов;
- написан на PowerShell, что затрудняет добавление новых пакетов в репозиторий.

На сегодняшний день, есть более хорошая альтернатива: менеджер пакетов [scoop](https://github.com/ScoopInstaller/Scoop). Вот некоторые из его преимуществ:
- позиционируется как пакетный менеджер для разработчиков - в репозитории содержится большое количество пакетов, необходимых для разработчиков - языки программирования, редакторы и IDE, и так далее;
- не требует административного доступа для установки;
- так же не требует административного доступа для установки пакетов - они устанавливаются в пользовательский каталог по умолчанию; установка пакетов "глобально" так же доступна - при необходимости;
- если устанавливаемый пакет содержит инструменты командной строки, они становятся доступны пользователю в любом эмуляторе терминала - cmd, Windows Terminal и т. д.;
- описания пакетов представляют собой файлы в формате JSON - если требуемый пакет отсутствует, зачастую сам разработчик может его и "законтрибьютить".

В Wiki проекта доступно более полное [сравнение с Chocolatey](https://github.com/ScoopInstaller/Scoop/wiki/Chocolatey-Comparison).

# Собственно, терминал

Не смотря на то, что для Windows существует множество эмуляторов терминала, они все страдают от одной общей проблемы, а именно - одного эмулятора терминала не достаточно, необходимо так же ещё и пользовательское окружение Unix. На сегодняшний день, самый простой и самый надёжный способ его получить - это [WSL](https://docs.microsoft.com/en-us/windows/wsl/). Сейчас буквально можно установить дистрибутив Linux прямо из [магазина Windows Store](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6). Однако, что там с терминалом?

Снова, тут доступно решение от самой MS, а именно Windows Terminal - так же доступен прямо из [магазина](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701). Он имеет отличную интеграцию с WSL, довольно удобен и интенсивно развивается.

**Comment by mokevnin** [comment]
Уже не актуально
