### ISSUE TITLE
The English-language locale uses Russian-language meta tags

### ISSUE THREAD

**Issue by fey** [Hexlet/hexletguides.github.io#364]

**Comment by hellion86** [comment]
Не совсем понял, что нужно поправить?

**Comment by fey** [comment]
og теги, которые используются для соц сетей.
Мб этот ишшус потеряет актуальность с переходом на nextjs

![image](https://user-images.githubusercontent.com/697178/181582543-db2572ba-9e27-4957-818e-43d00b1d7bf2.png)
