### ISSUE TITLE
Migrate hexletguides to next.js

### ISSUE THREAD

**Issue by fey** [Hexlet/hexletguides.github.io#365]

**Comment by seth2810** [comment]
@acidmaksim I think the verb "migrate" is more suitable for the action planned in the issue.

**Comment by seth2810** [comment]
@acidmaksim looks like all tasks completed and we can initiate replacement of main site with nextjs MVP?

**Comment by fey** [comment]
да, ребятам передал, что пора

**Comment by fey** [comment]
@dzencot закроешь ишшус, когда задеплоите и нужные редиректы поставите

**Comment by dzencot** [comment]
Деплой настроен на версел
