### ISSUE TITLE
[nextjs] Posts navigation component

### ISSUE THREAD

**Issue by seth2810** [Hexlet/hexletguides.github.io#419]
#365
<img width="816" alt="Screen Shot 2022-08-22 at 18 45 35" src="https://user-images.githubusercontent.com/845078/185963068-021d0e14-0143-4795-b544-3ccca83360a8.png">

**Comment by seth2810** [comment]
@hellion86 FYI

**Comment by hellion86** [comment]
send PR, please check it - https://github.com/Hexlet/hexletguides.github.io/pull/427
