### ISSUE TITLE
[nextjs] Privacy policy page

### ISSUE THREAD

**Issue by seth2810** [Hexlet/hexletguides.github.io#420]
#365 

https://guides.hexlet.io/privacy-policy/
https://guides.hexlet.io/ru/privacy-policy/

**Comment by acidmaksim** [comment]
@seth2810 Where can I get a Russian translation?

**Comment by seth2810** [comment]
@acidmaksim as can be seen from the links, there is no translation on current site. So you can temporarily use English, or as a Hexlet employee request it from those responsible for the content.

**Comment by acidmaksim** [comment]
The en site should have a Privacy Police button and lead to https://hexlet.io/pages/privacy.

**Comment by seth2810** [comment]
@acidmaksim Then maybe it makes sense to do it in two versions at once - the current and nextjs? Because the second one is still in the MVP prototype stage.

**Comment by acidmaksim** [comment]
Yes, I'll add the issues now. I have another question, how do I go to this page https://guides.hexlet.io/privacy-policy/?
Right now I don't see anything on the site

**Comment by seth2810** [comment]
I assume that access is via a direct link. 

Moving to nextjs involves creating an MVP to which it would be possible to switch the current site without problems and not get degraded by availability. Therefore, it is desirable to keep all the links to the pages, their contents and visual representation to the maximum.

**Comment by acidmaksim** [comment]
Дело в том, что тот текст, который сейчас есть(https://guides.hexlet.io/privacy-policy/
https://guides.hexlet.io/ru/privacy-policy/), он вообще не правильный. Должен быть редирект на https://hexlet.io/pages/privacy в английской версии

**Comment by seth2810** [comment]
Решено в #428
