### ISSUE TITLE
[nextjs] RSS feed

### ISSUE THREAD

**Issue by seth2810** [Hexlet/hexletguides.github.io#424]
#365 
http://guides.hexlet.io/feed.xml

**Comment by Aleksandr-Bondarev** [comment]
Добрый день, хочу попробовать сделать.

**Comment by seth2810** [comment]
@Aleksandr-Bondarev you're welcome. Сейчас основная задача сделать MVP next.js проекта guides без потери текущего функционала. Каким образом будет реализован feed отдается на усмотрение разработчика и его гласа разума 😉

**Comment by seth2810** [comment]
@ashikov назначишь ответственным?

**Comment by IxxyDev** [comment]
Какой статус у задачи?

**Comment by seth2810** [comment]
@IxxyDev так review идет - #432
