### ISSUE TITLE
add Privacy Policy button on page

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexletguides.github.io#426]
The en site should have a Privacy Police button and lead to https://hexlet.io/pages/privacy.
![image](https://user-images.githubusercontent.com/77053797/186172300-bbd35334-a6e2-4bd3-b6e3-fc9430742d31.png)

**Comment by seth2810** [comment]
Policy not Police 👮🏾‍♂️

**Comment by TimurDavlet** [comment]
Готов взять в работу

**Comment by seth2810** [comment]
@acidmaksim закрываем?
