### ISSUE TITLE
show user content depends on locale

### ISSUE THREAD

**Issue by fey** [Hexlet/hexletguides.github.io#440]
Redirect to /ru if ru locale

**Comment by TimurDavlet** [comment]
Не совсем понял. При каких условиях нужно делать редирект ?

**Comment by fey** [comment]
Если у юзера в системе\браузере ru язык, то редиректить на русскоязычный контент

**Comment by mokevnin** [comment]
Это можно будет сделать когда мы перейдем на next.js. Логика редиректов будет как на code-basics

**Comment by acidmaksim** [comment]
@fey у нас это реализовано?

**Comment by fey** [comment]
Это сделано, пользователя редиректит в зависимости от локали. Но я не уверен, что IP на это влияет. Думаю, что можно закрывать.
