### ISSUE TITLE
При прямом переходе на какой-то гайд по ссылке, редиректит на главную

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexletguides.github.io#444]
Например, если нажать на эту ссылку https://guides.hexlet.io/ru/vim, то произойдёт редирект на https://guides.hexlet.io/ru. Если переходить с главной страницы в гайд, то всё окей

**Comment by ashikov** [comment]
@seth2810 возможно ты сможешь помочь, плиз. Проблема важная, у нас очень много, где прямые ссылки на гайды используются.

**Comment by ashikov** [comment]
@acidmaksim fyi

**Comment by amshkv** [comment]
я пока закомментировал код, который этот редирект вызывает
https://github.com/Hexlet/hexletguides.github.io/pull/442

**Comment by amshkv** [comment]
@TimurDavlet это твой кот :)

**Comment by seth2810** [comment]
@amshkv да мог бы просто revert сделать ;)

**Comment by acidmaksim** [comment]
@amshkv вроде нет такой ошибки сейчас. Закрываю issues?
