### ISSUE TITLE
Поправить вёрстку на странице со всеми гайдами

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexletguides.github.io#515]
Мы добавили вывод картинок, но вёрстка не особо.
<img width="1440" alt="image (2)" src="https://user-images.githubusercontent.com/676554/196695169-9246b848-eb74-40b7-8bc1-08b961a1e892.png">
Надо всё выровнять, чтобы было красиво.

**Comment by ashikov** [comment]
@Psixodelik сможем поправить?

**Comment by acidmaksim** [comment]
@ashikov так как мы убрали картинки, я закрываю ишью
