### ISSUE TITLE
Невеерная ссылка на редактирование

### ISSUE THREAD

**Issue by trolzen** [Hexlet/hexletguides.github.io#519]
На странице [Что такое «Менеджер версий»](https://guides.hexlet.io/ru/version-managers/) в самом низу под текстом "Исходный код (github)" стоит неправильная ссылка — 
https://github.com/Hexlet/hexletguides.github.io/tree/main/data/posts/ru/2020-06-28-version-managers.md, 
должна быть 
https://github.com/Hexlet/hexletguides.github.io/tree/main/_i18n/ru/_posts/2020-06-28-version-managers.md

Возможно, это касается и других страниц, я пока не разобрался, откуда эта ссылка берётся.

**Comment by Asya-Kamaeva** [comment]
там настроен 301 редирект с https://github.com/Hexlet/hexletguides.github.io/tree/main/data/posts/ru/2020-06-28-version-managers.md на https://github.com/Hexlet/hexletguides.github.io/tree/main/_i18n/ru/_posts/2020-06-28-version-managers.md

**Comment by trolzen** [comment]
В  связи с недавним перездом с Jekyll на  Next.js проблема с конкретно этой страницей решилась. По истории видно, что [она была перенесена по этому пути из другого места](https://github.com/Hexlet/hexletguides.github.io/commits/main/data/posts/ru/2020-06-28-version-managers.md). Видимо, с другими страницами, если и были подобные проблемы, то они тоже ушли.
