### ISSUE TITLE
Ошибка при открытии гайда

### ISSUE THREAD

**Issue by evgeniyworkbel** [Hexlet/hexletguides.github.io#527]
Выкидывает ошибку при попытке перейти на https://guides.hexlet.io/webpack/ В консоли можно посмотреть вид ошибки

**Comment by acidmaksim** [comment]
@dzencot посмотри, пожалуйста, что здесь можно сделать

**Comment by acidmaksim** [comment]
@evgeniyworkbel привет, пришли , пожалуйста скриншот ошибки или запиши видео, чтобы посмотреть в чем ошибка
