### ISSUE TITLE
You need to restore the values of meta tags and article titles. They are in the article files on the old version

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexletguides.github.io#538]

**Comment by acidmaksim** [comment]
@dzencot Вань, расскажи, пожалуйста по задачу или она уже сделана?

**Comment by dzencot** [comment]
Да, была сделана.

**Comment by fey** [comment]
Так, задачку нужно доделать.
Что конкретно не так.
Есть заголовки для людей (header), а есть поисковиков. 
У каждого поста есть теги для поисковиков.

Т.е. на примере гайда по бутстрапуэ
```
title: |
  Bootstrap простыми словами: что это, для чего нужен, как работает фреймворк
header: Что такое Bootstrap, и как он работает
```
Тайтл это для машины, хедер это для людей.

Пример как у код бейзикса 
https://github.com/hexlet-basics/exercises-javascript/blob/main/description.ru.yml#L3-L15
Мы делаем такую же штуку.
![image](https://user-images.githubusercontent.com/697178/215798205-bb81fbea-fca5-41ad-bf8e-189ee0427a66.png)

**Comment by ViktorFAlex** [comment]
@fey Возьму в работу.
