### ISSUE TITLE
In the beginning of articles, after leads there was anchor content of articles - it should be returned.

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexletguides.github.io#539]
There is an example here https://ru.hexlet.io/blog/posts/chto-takoe-mvc-rasskazyvaem-prostymi-slovami

**Comment by askorutin26** [comment]
возьму в работу

**Comment by Vox1oot** [comment]
Я могу взять в работу ?!

**Comment by askorutin26** [comment]
> Я могу взять в работу ?!
уже работаю над этой задачей
