### ISSUE TITLE
Make sitemap.xml. all articles and main page should be uploaded. 

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexletguides.github.io#540]
For each link you need a lastmodifyfy attribute, and you need to output links to all the images from the articleDocumentation - https://yandex.ru/support/images/sitemap-images.html
https://yandex.ru/support/webmaster/controlling-robot/sitemap.html

**Comment by Shamilist** [comment]
Привет, по ссылке выходит ошибка

**Comment by acidmaksim** [comment]
@Shamilist поправил

**Comment by Vox1oot** [comment]
Я попробую взять!

**Comment by Vox1oot** [comment]
Добавил в sitemap URL's изображений для индексирования.
Я так понимаю, что теги lastmod уже добавлены и добавлять их не надо ?!

**Comment by fey** [comment]
да, добавлены
https://sicp.hexlet.io/sitemap.xml

**Comment by Vox1oot** [comment]
Речь идёт про этот sitemap https://guides.hexlet.io/sitemap.xml
