### ISSUE TITLE
We need to implement language markup

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexletguides.github.io#541]
Documentation - https://developers.google.com/search/docs/specialty/international/localized-versions?hl=ruPersonally I prefer html tagging, but it might be easier with sitemap

**Comment by Tatiana-Popova** [comment]
возьму

**Comment by acidmaksim** [comment]
@Tatiana-Popova получается решить задачу?

**Comment by Tatiana-Popova** [comment]
> @Tatiana-Popova получается решить задачу?

Задала вопрос в слаке

**Comment by Vox1oot** [comment]
Я могу взять, если Таня не против)

**Comment by Tatiana-Popova** [comment]
> Я могу взять, если Таня не против)

Пока что разбираемся, через несколько дней отпишусь

**Comment by Tatiana-Popova** [comment]
Не получается сделать, свободно

**Comment by Vox1oot** [comment]
Возьму в работу

**Comment by Vox1oot** [comment]
Сделать не смог. Свобдно

**Comment by HunterGan** [comment]
Возьму

**Comment by acidmaksim** [comment]
@HunterGan получается решить задачу? Помощь нужна?

**Comment by HunterGan** [comment]
@acidmaksim Пр отправил
