### ISSUE TITLE
We need to implement a micrometric for articles, Article scheme, format - json-ld

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexletguides.github.io#542]
Documentation - https://developers.google.com/search/docs/appearance/structured-data/article?hl=ru

**Comment by HunterGan** [comment]
Возьму

**Comment by acidmaksim** [comment]
@HunterGan привет) получается задачка?

**Comment by HunterGan** [comment]
Думаю да, в выходные планирую сдать!
