### ISSUE TITLE
Подключить шрифт Onest для гайдов

### ISSUE THREAD

**Issue by Psixodelik** [Hexlet/hexletguides.github.io#552]
На Хекслете используется шрифт Onest в качестве основного для набора текста. В гайдах тоже стоит перейти для него. Для этого надо:

1. Закинуть шрифты
2. Подключить их
3. Добавить шрифт в переменные Bootstarp в качестве основного шрифта без засечек

Шрифт с открытой лицензией. Скачать его можно с официального сайта https://onest.md/ru

**Comment by Vox1oot** [comment]
Возьму в работу

**Comment by Vox1oot** [comment]
Сделал
