### ISSUE TITLE
Hover эффект для навигации

### ISSUE THREAD

**Issue by Vox1oot** [Hexlet/hexletguides.github.io#557]
https://user-images.githubusercontent.com/6084476/206869654-9cda4f5c-4eef-4816-bee3-4c8d85a2690c.mp4

Предлагаю немного оживить навигацию.
Добавил hover эффект.

**Comment by fey** [comment]
Решили не усложнять верстку и не делать эту штуку.
Если есть идеи по улучшению - используйте возможности бутстрапа.
