### ISSUE TITLE
Seo: fix duplicated descriptions

### ISSUE THREAD

**Issue by fey** [Hexlet/hexletguides.github.io#561]
Guides and articles for developers — 3 таких описаний
/
/about/
/encoding/

Полезные статьи и гайды для разработчиков
[/ru/](https://guides.hexlet.io/ru/)
[/ru/about/](https://guides.hexlet.io/ru/about/)

---

Ишшус пока чтобы не забыть. Тексты дескрипшенов будут позднее.

Для НЕ главных страниц можно щас добавить временное описание, чтобы не было дублирования + для статьи что-то придумать.

**Comment by fey** [comment]
@ssssank нужно попросить кого-то проверить. этот ищщус.

**Comment by M4XPRD** [comment]
Беру на себя задачу

**Comment by M4XPRD** [comment]
@fey , а в чём конкретно заключается задача? Прошёлся по описаниям и там всё есть

**Comment by fey** [comment]
у каждой страницы должно быть уникальное описание. в дескрипшене.

**Comment by M4XPRD** [comment]
У вообще каждой страницы или у 

**EN**: `/`, `/about`, `/encoding/`, 
**RU**: `/ru`, `/ru/about`?

**Comment by fey** [comment]
у каждой страницы. Т.е. у гайдов должны быть уникальные дескрипшены, хотя бы что-то и у каждой страницы

**Comment by ssssank** [comment]
@fey можем закрыть?

**Comment by fey** [comment]
Думаю, что да
