### ISSUE TITLE
opening of the external links in a new tab

### ISSUE THREAD

**Issue by ShushaAlex** [Hexlet/hexletguides.github.io#585]
### Problem description

On the page: https://guides.hexlet.io/ru/how-to-learn-sicp/
External links in the main text open in the same tab

Links:
1. https://racket-lang.org/
2. https://github.com/hexlet-boilerplates/sicp-racket
3. https://github.com/search?q=sicp
4. https://docs.racket-lang.org/rackunit/

### Proposed solution

External links in text should open in a new tab

**Comment by zapupenec** [comment]
Беру

**Comment by fey** [comment]
https://github.com/Hexlet/hexletguides.github.io/issues/585
