### ISSUE TITLE
Поправить якоря ссылок в статьях

### ISSUE THREAD

**Issue by fey** [Hexlet/hexletguides.github.io#609]
### Problem description

из Яндекс Вебмастер пришел отчет, что у нас в статьях есть нерабочие якоря.

### Proposed solution

Поправить якоря. Т.е. при нажатии на ссылку в оглавлении статьи, мы переходим к нужному разделу. Если этого не происходит - значит якорь сломан.
Пример сломанного якоря - https://guides.hexlet.io/docker/#what's-all-this-for?
Пример рабочего якоря - https://guides.hexlet.io/docker/#docker-compose

Ниже будет список якорей. Он не очень понятно выглядит, потому что отчет пришел по фиду, но думаю инфы достаточно, чтобы найти нужные якоря/статьи - https://guides.hexlet.io/feed.xml

```


стр. | поз. |  
-- | -- | --
6 | 8 | nch</a></li> <li><a href="#what&#x27;s-all-this-for?">What&#x27;s all this for?<
10 | 8 | ent</a></li> <li><a href="#interaction%C2%A0between-the%C2%A0components%C2%A0of-
14 | 8 | ion</a></li> <li><a href="#docker:-what%E2%80%99s-under-the-hood?">Docker: what’
350 | 8 | er.</p> <ul> <li><a href="#hosts-file-%E2%80%94-the-first-step-to-creating-the-d
553 | 8 | le.</p> <ul> <li><a href="#how-you-shouldn%E2%80%99t-work-with-errors">How you s
855 | 8 | FAQ</a></li> <li><a href="#related-guides">Related guides</a></li> </ul> <h2 id=
979 | 8 | > </ol> <ul> <li><a href="#step-1:-self-awareness">Step 1: Self-awareness</a></l
980 | 8 | ess</a></li> <li><a href="#step-2:-mindset">Step 2: Mindset</a></li> <li><a href
981 | 8 | set</a></li> <li><a href="#**step-3:-openness**"><strong>Step 3: Openness</stron
1051 | 8 | ion</a></li> <li><a href="#what-is-%60make%60-and-*makefile*">What is <code>make

**Comment by ilya-rodin** [comment]
Делаешь задачу? Или может я возьму?

**Comment by rizhik356** [comment]
да, боюсь у меня не получится, бери
