### ISSUE TITLE
Bug: сломалась генерация якорей внутри статей

### ISSUE THREAD

**Issue by ssssank** [Hexlet/hexletguides.github.io#618]
### Summary

ПР #611 сломал генерацию ссылок-якорей внутри статей. В английский гайдах всё работает, а с кириллицей - проблемы

![image](https://github.com/Hexlet/hexletguides.github.io/assets/17835285/106af8af-feea-4a43-a127-255e2a069244)

### Reproduction steps

```bash
.
```

### Expected result

Ссылки генерируются правильно на каждом языке

### Actual result

Ссылки генерируются правильно только на английском языке

**Comment by fey** [comment]
Откатил в https://github.com/Hexlet/hexletguides.github.io/pull/617#issuecomment-1628723918

**Comment by zapupenec** [comment]
Могу попробовать глянуть. Может получиться)
Только не понимаю как мне правильно с этим работать. Там был некий ПР, а потом его откатили. Что с этим делать?)

**Comment by fey** [comment]
форкните репозиторий, создайте у себя ветку, работайте в ней, создайте пулл реквест.
Я думаю, что надо разобраться с формированием якоерй. В идеале, чтобы якори были в латиннице и без символов типа `!?`, а что-то типа kebab-case
