### ISSUE TITLE
При нажатии на выбор языка перенаправляет на главную страницу 

### ISSUE THREAD

**Issue by AavadaKedavra** [Hexlet/hexletguides.github.io#627]
### Summary

Со статьи https://guides.hexlet.io/ru/how-to-learn-sicp/ при нажатии выбор языка перебрасывает на главную https://guides.hexlet.io **баг воспроизводится для остальных статей и раздела about (footer) тоже** 

### Reproduction steps

```bash
1. Открыть https://guides.hexlet.io/ru/how-to-learn-sicp/
2. Открыть https://hexletguides-f8vv66vxn-hexlet.vercel.app/git-guide/
3. Открыть https://hexletguides-f8vv66vxn-hexlet.vercel.app/http-api/
4. Открыть https://guides.hexlet.io/docker/
5. Открыть https://hexletguides-f8vv66vxn-hexlet.vercel.app/dns/
6. Открыть https://guides.hexlet.io/deploy/
7. Открыть https://hexletguides-f8vv66vxn-hexlet.vercel.app/about/
.
.
.
8. Нажать выбор языка (RU/EN)
```

### Expected result

Должны остаться на статье, язык статьи изменился 

### Actual result

Перенаправляет на https://guides.hexlet.io (язык главной страницы изменился)
При нажатии back в браузере, возвращаемся на статью - язык прежний 
![image](https://github.com/Hexlet/hexletguides.github.io/assets/126116401/4c8ccaf2-b69b-4210-9a72-b654917d1329)
![image](https://github.com/Hexlet/hexletguides.github.io/assets/126116401/31873f79-3dbd-4946-be4e-af01af8e19b3)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by fey** [comment]
Да, это такая фича. То, что пользователь будет сидеть на сайте не своего языка- мало вероятно. Плюс многие страницы - это контент. Их может не быть, поэтому редирект идет на страницу, которая 100% есть.

**Comment by AavadaKedavra** [comment]
https://github.com/Hexlet/hexletguides.github.io/wiki/%D0%9B%D0%BE%D0%BA%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F добавил информацию об этом в вики
