### ISSUE TITLE
В английской версии отображается меньшее количество статей на сайте 

### ISSUE THREAD

**Issue by AavadaKedavra** [Hexlet/hexletguides.github.io#628]
### Summary

В английской и русской версиях отображается разное количество статей, в английской значительно меньше 

### Reproduction steps

```bash
1. Открыть https://guides.hexlet.io/
2. Переключать язык интерфейса En/RU
```

### Expected result

Все гиперссылки и другие элементы интерфейса отображаются одинаково в полном объеме 

### Actual result

В английской версии отображается значительно меньшее количество статей
![image](https://github.com/Hexlet/hexletguides.github.io/assets/126116401/7405a2f7-5512-4064-a4e0-e930afc912ce)
![image](https://github.com/Hexlet/hexletguides.github.io/assets/126116401/d2deb579-65f3-40bf-8e15-64db215e221b)
![image](https://github.com/Hexlet/hexletguides.github.io/assets/126116401/9e3a5942-2187-49e7-aa4e-33863f65272b)

### Browsers

Chrome, Opera

### OS

Windows

**Comment by ssssank** [comment]
Да, статьи потихоньку переводятся, но это не очень быстрый процесс, поэтому их меньше на английском языке

**Comment by fey** [comment]
Английский и русскоязычный раздел можно воспринимать, как два разных сайта. Страницы статей - это контент. Поэтому это нормально, что будут разные страницы на разных языках.
Эту информацию можно записать в доку проекта. Доступ в wiki я кажется вам выдал.

**Comment by AavadaKedavra** [comment]
https://github.com/Hexlet/hexletguides.github.io/wiki/%D0%9B%D0%BE%D0%BA%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F
