### ISSUE TITLE
Внести дополнительную информацию по установке в Гайд по Менеджеру версий.

### ISSUE THREAD

**Issue by funnyDevGirl** [Hexlet/hexletguides.github.io#630]
### Problem description

Предлагаю добавить информацию в Гайд по курсу "Java-разработчик": https://guides.hexlet.io/ru/version-managers/
Установка Менеджера версий asdf по Гайду не будет успешна, т.к. не прописано, что после добавления строки "echo '. $HOME/.asdf/asdf.sh' >> ~/.bashrc" нужно ещё активировать внесённые изменения.
Без этой команды asdf не активен, им невозможно пользоваться.

### Proposed solution

После строки "echo '. $HOME/.asdf/asdf.sh' >> ~/.bashrc" указать на необходимость активировать внесённые изменения командой: source ~/.bashrc.

**Comment by fey** [comment]
@funnyDevGirl Добрый день. Получится у вас предложить изменения в пулл реквесте?
