### ISSUE TITLE
Ошибки в тексте

### ISSUE THREAD

**Issue by Yawerica** [Hexlet/hexletguides.github.io#654]
### Summary

Ошибки в тексте

### Reproduction steps

```bash
1.Перейти на страницу статьи https://guides.hexlet.io/ru/cryptography/
```

### Expected result

1. храните заменить на хранить
2. убрать предлог "в" или дописать в поисковой строке

### Actual result

![hexlet](https://github.com/Hexlet/hexletguides.github.io/assets/148934630/c016447f-e3c6-4dac-bc68-d1027ef0e191)
![hexlet1](https://github.com/Hexlet/hexletguides.github.io/assets/148934630/cc4c0f92-570c-4b08-af78-b44d0729f692)

### Browsers

Chrome

### OS

Windows

**Comment by DimRux** [comment]
Привет! Возьму в работу.

**Comment by fey** [comment]
@Yawerica вроде поправили?

**Comment by Yawerica** [comment]
@fey да👍🏻
