### ISSUE TITLE
Translate issues into English

### ISSUE THREAD

**Issue by HelenOne** [Hexlet/hexletguides.github.io#657]
### Problem description

It has been decided that all open-source projects will be translated into English in order to make them more accessible to a global audience.

### Proposed solution

The task is to create a new English issue for each existing issue. You need to translate the title and the description into English, and provide the context of the confirmation in the comments. Also, you should refer to the original Russian task. Old issues will be archived.

You can use the [Yandex Translate editor](https://translate.yandex.ru/editor).

**Comment by kodsurfer** [comment]
Hi, I can help

**Comment by fey** [comment]
@kodsurfer please check notifications. I just sent you invite

**Comment by fey** [comment]
@kodsurfer you should accept invite
![image](https://github.com/user-attachments/assets/243d3e4c-c9de-43e2-9435-dd168085c3a5)

**Comment by kodsurfer** [comment]
@fey thanks!

**Comment by kodsurfer** [comment]
work in progess: issues are  being translated

**Comment by kodsurfer** [comment]
work in progress

**Comment by kodsurfer** [comment]
work in progress

**Comment by kodsurfer** [comment]
and so on -- work in progress

**Comment by fey** [comment]
> and so on -- work in progress

not relevant, We will close this repository soon and will move guides to hexlet's main blog
